### ISSUE TITLE
Strict mode: Error: Cannot replace x → y

### ISSUE THREAD

**Issue by envil** [Va1/string-replace-loader#47]
I'm replacing some import in my scss file and it doesn't work:

```
Module build failed: Error: Cannot replace default-theme → client1
   at processOptions (/tmp/app/node_modules/string-replace-loader/index.js:12:13)
   at Object.module.exports (/tmp/app/node_modules/string-replace-loader/index.js:32:14)
```

here is the config:
```
       {
          test: /styles\.scss$/,
          use: [
            {
              loader: 'string-replace-loader',
              options: {
                search: 'default-theme',
                replace: 'foo-theme',
                strict: true
              }
            }
          ]
        }
```

**Comment by envil** [comment]
Possibly duplicate of https://github.com/Va1/string-replace-loader/issues/7
